### PR TITLE
Add skeleton for typography page

### PR DESCRIPTION
**Pull request by tinahsieh**
This is the refined version based on the result of DS team meeting.

### CODE REVIEW

**Comment by brassy-** [comment]
@aminalhazwani: we are ready to merge

**Comment by aminalhazwani** [comment]
@tinahsieh I find the [skeleton](https://bwinton.github.io/DesignSystem/illustration.html) that @brassy- did for the illustration page to be pretty solid. She added the headlines but also a small excerpt underneath each headline that gives a little bit of context. Do you think that it would be possible to do such thing for the typography page? 

As discussed, I would also promote first, the styles that are valid cross-platform and then, follow up with the ones that are platform-specific.

**Comment by tinahsieh** [comment]
Well... it's hard for me to add content without having more information about typography.
I'm good with hiding the structure. I think it will make more sense to do that in the next sprint since we'll discuss the typography guideline during Toronto workweek.

**Comment by aminalhazwani** [comment]
Ok, will not merge as long as we don't have more contextual content. Thanks!

**Comment by aminalhazwani** [comment]
This pull request will be probably close and we will follow up on `typography-production`. More soon to come tomorrow CET.

**Pull request closed without merging**
